# Generated by Django 2.1.7 on 2019-05-15 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='feed',
            name='status',
            field=models.IntegerField(default=0),
        ),
    ]
