# Generated by Django 2.1.7 on 2019-05-16 02:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0002_feed_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='feed',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='fromUser',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='toUser',
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
