# Generated by Django 2.1.7 on 2019-05-17 05:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userInfo', '0003_auto_20190515_0837'),
        ('feed', '0003_auto_20190516_0236'),
    ]

    operations = [
        migrations.AddField(
            model_name='feed',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='userInfo.User'),
            preserve_default=False,
        ),
    ]
