# Generated by Django 2.1.7 on 2019-05-23 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0004_feed_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedimg',
            name='img',
            field=models.CharField(max_length=200),
        ),
    ]
