# Generated by Django 2.1.7 on 2019-05-24 06:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0005_auto_20190523_0514'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedimg',
            name='feed',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imgs', to='feed.Feed'),
        ),
    ]
