# Generated by Django 2.1.7 on 2019-05-15 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userInfo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='wechat',
            field=models.CharField(default='', max_length=20, verbose_name='微信号'),
            preserve_default=False,
        ),
    ]
