# Generated by Django 2.1.7 on 2019-05-15 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userInfo', '0002_user_wechat'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='qq',
            field=models.CharField(default='', max_length=20, verbose_name='QQ'),
        ),
        migrations.AlterField(
            model_name='user',
            name='wechat',
            field=models.CharField(default='', max_length=20, verbose_name='微信号'),
        ),
    ]
